version: "3.9"
services:
  fuzzyman:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fuzzyman
    environment:
      FLASK_DEBUG: 0
    restart: always
    volumes:
      - ./:/app
    networks:
      my-network:
        aliases:
          - flask-app
    ports:
      - 5000:5000
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./infra/local/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./infra/local/nginx.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./infra/local/selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - my-network
networks:
  my-network: