version: "3.3"
services:
  fuzzyman:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fuzzyman
    environment:
      FLASK_DEBUG: 0
      POSTMAN_API_KEY: "${POSTMAN_API_KEY}"
    restart: always
    volumes:
      - ./:/app
    networks:
      my-network:
        aliases:
          - flask-app
    ports:
      - 5000:5000
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    networks:
      - my-network
networks:
  my-network: